version: "3.3"
services:
  influxdb:
    container_name: influxdb
    image: influxdb
    networks:
      - tig_net    
    ports:
      - "8086:8086"
    volumes:
      - ./tig/data/influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=telegraf
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=influx
      - INFLUXDB_USER=telegraf
      - INFLUXDB_USER_PASSWORD=telegraf      
    restart: always

  grafana:
    container_name: grafana
    image: grafana/grafana
    networks:
      - tig_net    
    ports:
      - "3000:3000"
    volumes:
      - grafana_volume:/var/lib/grafana
    restart: always 

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:latest
    networks:
      - tig_net    
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mosquitto_volume:/mosquitto
    restart: always

  telegraf:
    container_name: telegraf
    image: telegraf
    networks:
      - tig_net    
    volumes:
      - ./tig/config/telegraf:/etc/telegraf:ro
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    depends_on:
      - influxdb
      - mqtt

  chronograf:
    container_name: chronograf
    image: chronograf:latest
    ports:
      - "8888:8888"
    volumes:
      - "./chronograf:/var/lib/chronograf"
    networks:
      - tig_net
    
networks:
    tig_net:

volumes:
    grafana_volume:
    telegraf_volume:
    mosquitto_volume:
